# Generated by Django 4.0.4 on 2022-05-26 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la Categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idJuego', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del juego')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo del Juego')),
                ('nombreJuego', models.CharField(max_length=30, verbose_name='Nombre del Juego')),
                ('precioJuego', models.IntegerField(verbose_name='Precio del Juego')),
                ('foto', models.ImageField(null=True, upload_to='juegos')),
                ('video', models.URLField(verbose_name='Video del Juego')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Juego')),
                ('masInfo1', models.TextField(verbose_name='Mas Informacion del Juego 1')),
                ('masInfo2', models.TextField(verbose_name='Mas Informacion del Juego 2')),
                ('masInfo3', models.TextField(verbose_name='Mas Informacion del Juego 3')),
                ('masInfo4', models.TextField(verbose_name='Mas Informacion del Juego 4')),
                ('masInfo5', models.TextField(verbose_name='Mas Informacion del Juego 5')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
