# Generated by Django 4.0.4 on 2022-06-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='masInfo1',
            field=models.TextField(blank=True, null=True, verbose_name='Mas Informacion del Juego 1'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='masInfo2',
            field=models.TextField(blank=True, null=True, verbose_name='Mas Informacion del Juego 2'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='masInfo3',
            field=models.TextField(blank=True, null=True, verbose_name='Mas Informacion del Juego 3'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='masInfo4',
            field=models.TextField(blank=True, null=True, verbose_name='Mas Informacion del Juego 4'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='masInfo5',
            field=models.TextField(blank=True, null=True, verbose_name='Mas Informacion del Juego 5'),
        ),
    ]
