# Generated by Django 4.0.4 on 2022-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producto_masinfo1_alter_producto_masinfo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='video',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
