# Generated by Django 4.0.4 on 2022-06-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='foto',
        ),
    ]
