# Generated by Django 4.0.4 on 2022-07-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id',
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo',
            field=models.IntegerField(null=True, primary_key=True, serialize=False, verbose_name='Codigo de la Categoria'),
        ),
    ]
